### ISSUE TITLE
Most recent Mflowgen Broken on CentOS with  Python Version <3.7

### ISSUE THREAD

**Issue by Chris-Not-Mikey** [mflowgen/mflowgen#130]
I am currently using an older mflowgen version and that works fine. However, following the instructions (https://mflowgen.readthedocs.io/en/latest/quick-start.html)  for a fresh install no longer works.  It does not seem possible to fix on my end (ie upgrading Python version) without sudo privileges. 

[venv] [cmc2374@iron-502-26 mflowgen]$ pip install -e .
Obtaining file:///scratch/users/cmc2374/dep_test/mflowgen
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /scratch/users/cmc2374/dep_test/venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/scratch/users/cmc2374/dep_test/mflowgen/setup.py'"'"'; __file__='"'"'/scratch/users/cmc2374/dep_test/mflowgen/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rsttz942
       cwd: /scratch/users/cmc2374/dep_test/mflowgen/
  Complete output (40 lines):
  WARNING: '.' not a valid package name; please use only .-separated package names in setup.py
  running egg_info
  creating /tmp/pip-pip-egg-info-rsttz942/mflowgen.egg-info
  writing /tmp/pip-pip-egg-info-rsttz942/mflowgen.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-rsttz942/mflowgen.egg-info/dependency_links.txt
  writing entry points to /tmp/pip-pip-egg-info-rsttz942/mflowgen.egg-info/entry_points.txt
  writing requirements to /tmp/pip-pip-egg-info-rsttz942/mflowgen.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-rsttz942/mflowgen.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-rsttz942/mflowgen.egg-info/SOURCES.txt'
  package init file '__init__.py' not found (or not a regular file)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/scratch/users/cmc2374/dep_test/mflowgen/setup.py", line 114, in <module>
      'mflowgen-python = mflowgen.mflowgen_python:_mflowgen_python_main',
    File "/scratch/users/cmc2374/dep_test/venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/scratch/users/cmc2374/dep_test/venv/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 278, in run
      self.find_sources()
    File "/scratch/users/cmc2374/dep_test/venv/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
      mm.run()
    File "/scratch/users/cmc2374/dep_test/venv/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 524, in run
      self.add_defaults()
    File "/scratch/users/cmc2374/dep_test/venv/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 563, in add_defaults
      rcfiles = list(walk_revctrl())
    File "/scratch/users/cmc2374/dep_test/venv/lib64/python3.6/site-packages/setuptools/command/sdist.py", line 20, in walk_revctrl
      for item in ep.load()(dirname):
    File "/scratch/users/cmc2374/dep_test/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
      return self.resolve()
    File "/scratch/users/cmc2374/dep_test/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/scratch/users/cmc2374/dep_test/mflowgen/.eggs/setuptools_scm-7.0.5-py3.6.egg/setuptools_scm/__init__.py", line 5
      from __future__ import annotations
      ^
  SyntaxError: future feature annotations is not defined
  ----------------------------------------
WARNING: Discarding file:///scratch/users/cmc2374/dep_test/mflowgen. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[venv] [cmc2374@iron-502-26 mflowgen]$ python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22)

**Comment by ctorng** [comment]
It looks like this issue has come up in many different tools that did not specify a patch version for Python 3.6.

As you were searching for an answer, you probably found that the future feature annotation is Python 3.7+ (but backported to 3.6.9 apparently). It does work on Python 3.7.4 for me, but not on Python 3.6.8.

With this, we probably have to specify the requirement to be Python 3.6.9+, or 3.7+.

For you specifically, have you tried checking your server to see if there are other python versions available? Sometimes admins will provide extra versions in usr bin for "python3.6", "python3.7" in addition to "python3".

I tend to install my own local versions of Python and use pyenv (https://github.com/pyenv/pyenv) to switch between user and system versions.

**Comment by ctorng** [comment]
Cleaning up this issue. We had actually bumped to a Python 3.7 version requirement when we moved to mflowgen 0.6.0.
