### ISSUE TITLE
when I execute command "pip install -e ."  have a error as below(I don't have Internet access)

### ISSUE THREAD

**Issue by sujf** [mflowgen/mflowgen#152]
Obtaining file:///home/sujf/Documents/digital/mflowgen-master
    Complete output from command python setup.py egg_info:
    /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    WARNING: '.' not a valid package name; please use only .-separated package names in setup.py
    running egg_info
    writing mflowgen.egg-info/PKG-INFO
    writing dependency_links to mflowgen.egg-info/dependency_links.txt
    writing entry points to mflowgen.egg-info/entry_points.txt
    writing requirements to mflowgen.egg-info/requires.txt
    writing top-level names to mflowgen.egg-info/top_level.txt
    package init file '__init__.py' not found (or not a regular file)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/sujf/Documents/digital/mflowgen-master/setup.py", line 114, in <module>
        'mflowgen-python = mflowgen.mflowgen_python:_mflowgen_python_main',
      File "/home/sujf/Documents/digital/mflowgen-master/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/sujf/Documents/digital/mflowgen-master/venv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 278, in run
        self.find_sources()
      File "/home/sujf/Documents/digital/mflowgen-master/venv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
        mm.run()
      File "/home/sujf/Documents/digital/mflowgen-master/venv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 524, in run
        self.add_defaults()
      File "/home/sujf/Documents/digital/mflowgen-master/venv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 563, in add_defaults
        rcfiles = list(walk_revctrl())
      File "/home/sujf/Documents/digital/mflowgen-master/venv/lib/python3.6/site-packages/setuptools/command/sdist.py", line 20, in walk_revctrl
        for item in ep.load()(dirname):
      File "/home/sujf/Documents/digital/mflowgen-master/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
        return self.resolve()
      File "/home/sujf/Documents/digital/mflowgen-master/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/sujf/Documents/digital/mflowgen-master/.eggs/setuptools_scm-7.1.0-py3.6.egg/setuptools_scm/__init__.py", line 5
        from __future__ import annotations
        ^
    SyntaxError: future feature annotations is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/sujf/Documents/digital/mflowgen-master/

**Comment by alexcarsello** [comment]
Please use Python 3.7 or above to fix this issue.

**Comment by ctorng** [comment]
Hopefully this has resolved your errors.. Closing this issue.
